env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  "import/extensions": "off",
  "import/no-unresolved": "off",
  "@typescript-eslint/no-non-null-assertion": "off'
}
